package co.edu.uniquindio.lexico

enum class Categoria {
    ENTERO,
    REAL,
    HEXADECIMAL,

    IDENTIFICADOR,
    PALABRA_RESERVADA,

    CADENA_CARACTERES,

    OPERADOR_ASIGNACION,

    OPERADOR_ARTIMETICO,
    OPERADOR_INCREMENTO,
    OPERADOR_DECREMENTO,

    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,

    PARENTESIS,
    LLAVES,
    FIN_SENTENCIA,
    SEPARADOR,

    COMENTARIOS,

    DESCONOCIDO
}